site_name: K3 Node
# steal from Patrick Kidger
theme:
  name: "material"
  features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
  palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode

plugins:
  - mkdocstrings
  - search  # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs  # Cross-links to headings
  - mknotebooks  # Jupyter notebooks
  - mkdocs-jupyter
docs_dir: _docs
site_dir: docs

repo_url: https://github.com/anas-rz/k3im
repo_name: anas-rz/k3im
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate


nav:
  - k3_node.layers: layers.md
  - Aggregation Layers: aggr_layers.md
  - Convolution Layers: conv_layers.md
  - Normalization Layers: norm_layers.md
  - Example TensorFlow: examples/tensorflow/ogb_arxiv_spektral_dataset.ipynb
  - Example PyTorch: examples/torch/planetoid_PyTorch_Geometric.ipynb
