[pytest]
testpaths = k3_node
norecursedirs = pytorch_geometric env .git tests_reference tests_training
pythonpath = .
filterwarnings =
    ignore:.*__array__ implementation doesn't accept a copy keyword.*:DeprecationWarning
    ignore:.*'torch-cluster' is no longer necessary and is being ignored.*:DeprecationWarning
    ignore:.*torch\.jit\.script.*is deprecated.*:FutureWarning
