from k3_node.transforms.base_transform import BaseTransform, functional_transform
from k3_node.transforms.compose import Compose, ComposeFilters

from k3_node.transforms.general import (
    ToDevice,
    ToSparseTensor,
    Constant,
    NormalizeFeatures,
    SVDFeatureReduction,
    RemoveTrainingClasses,
    RandomNodeSplit,
    RandomLinkSplit,
    NodePropertySplit,
    IndexToMask,
    MaskToIndex,
    Pad,
    Padding,
    UniformPadding,
    MappingPadding,
)

from k3_node.transforms.graph import (
    ToUndirected,
    OneHotDegree,
    TargetIndegree,
    LocalDegreeProfile,
    AddSelfLoops,
    AddRemainingSelfLoops,
    RemoveSelfLoops,
    RemoveIsolatedNodes,
    RemoveDuplicatedEdges,
    KNNGraph,
    RadiusGraph,
    ToDense,
    TwoHop,
    LineGraph,
    LaplacianLambdaMax,
    GDC,
    SIGN,
    GCNNorm,
    AddMetaPaths,
    AddRandomMetaPaths,
    RootedEgoNets,
    RootedRWSubgraph,
    LargestConnectedComponents,
    VirtualNode,
    AddLaplacianEigenvectorPE,
    AddRandomWalkPE,
    AddGPSE,
    FeaturePropagation,
    HalfHop,
)

from k3_node.transforms.spatial import (
    Distance,
    Cartesian,
    LocalCartesian,
    Polar,
    Spherical,
    PointPairFeatures,
    Center,
    NormalizeRotation,
    NormalizeScale,
    RandomJitter,
    RandomFlip,
    LinearTransformation,
    RandomScale,
    RandomRotate,
    RandomShear,
    FaceToEdge,
    SamplePoints,
    FixedPoints,
    GenerateMeshNormals,
    Delaunay,
    ToSLIC,
    GridSampling,
    RandomTranslate,
)

general_transforms = [
    'BaseTransform',
    'Compose',
    'ComposeFilters',
    'ToDevice',
    'ToSparseTensor',
    'Constant',
    'NormalizeFeatures',
    'SVDFeatureReduction',
    'RemoveTrainingClasses',
    'RandomNodeSplit',
    'RandomLinkSplit',
    'NodePropertySplit',
    'IndexToMask',
    'MaskToIndex',
    'Pad',
]

graph_transforms = [
    'ToUndirected',
    'OneHotDegree',
    'TargetIndegree',
    'LocalDegreeProfile',
    'AddSelfLoops',
    'AddRemainingSelfLoops',
    'RemoveSelfLoops',
    'RemoveIsolatedNodes',
    'RemoveDuplicatedEdges',
    'KNNGraph',
    'RadiusGraph',
    'ToDense',
    'TwoHop',
    'LineGraph',
    'LaplacianLambdaMax',
    'GDC',
    'SIGN',
    'GCNNorm',
    'AddMetaPaths',
    'AddRandomMetaPaths',
    'RootedEgoNets',
    'RootedRWSubgraph',
    'LargestConnectedComponents',
    'VirtualNode',
    'AddLaplacianEigenvectorPE',
    'AddRandomWalkPE',
    'AddGPSE',
    'FeaturePropagation',
    'HalfHop',
]

vision_transforms = [
    'Distance',
    'Cartesian',
    'LocalCartesian',
    'Polar',
    'Spherical',
    'PointPairFeatures',
    'Center',
    'NormalizeRotation',
    'NormalizeScale',
    'RandomJitter',
    'RandomFlip',
    'LinearTransformation',
    'RandomScale',
    'RandomRotate',
    'RandomShear',
    'FaceToEdge',
    'SamplePoints',
    'FixedPoints',
    'GenerateMeshNormals',
    'Delaunay',
    'ToSLIC',
    'GridSampling',
]

__all__ = general_transforms + graph_transforms + vision_transforms + [
    'RandomTranslate',
    'Padding',
    'UniformPadding',
    'MappingPadding',
    'functional_transform',
]

