from typing import Dict, List, Optional, Tuple
import keras
from keras import ops


def group(xs: List[any], aggr: Optional[str]) -> Optional[any]:
    if len(xs) == 0:
        return None
    elif aggr is None:
        return ops.stack(xs, axis=1)
    elif len(xs) == 1:
        return xs[0]
    elif aggr == "cat":
        return ops.concatenate(xs, axis=-1)
    elif aggr == "sum":
        return ops.sum(ops.stack(xs, axis=0), axis=0)
    elif aggr == "mean":
        return ops.mean(ops.stack(xs, axis=0), axis=0)
    elif aggr == "min":
        return ops.min(ops.stack(xs, axis=0), axis=0)
    elif aggr == "max":
        return ops.max(ops.stack(xs, axis=0), axis=0)
    else:
        raise ValueError(f"Unsupported aggregation: {aggr}")


class HeteroConv(keras.layers.Layer):
    r"""A generic wrapper for computing graph convolution on heterogeneous graphs.

    Args:
        convs (Dict[Tuple[str, str, str], keras.layers.Layer]): A dictionary holding a
            bipartite GNN layer for each individual edge type.
        aggr (str, optional): The aggregation scheme to use for grouping node
            embeddings generated by different relations (:obj:`"sum"`, :obj:`"mean"`,
            :obj:`"min"`, :obj:`"max"`, :obj:`"cat"`, :obj:`None`). (default: :obj:`"sum"`)
    """

    def __init__(
        self,
        convs: Dict[Tuple[str, str, str], keras.layers.Layer],
        aggr: Optional[str] = "sum",
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.convs = convs
        self.aggr = aggr

    def call(self, *args_dict, **kwargs_dict) -> Dict[str, any]:
        out_dict: Dict[str, List[any]] = {}

        for edge_type, conv in self.convs.items():
            src, rel, dst = edge_type
            has_edge_level_arg = False

            args = []
            for value_dict in args_dict:
                if edge_type in value_dict:
                    has_edge_level_arg = True
                    args.append(value_dict[edge_type])
                elif src == dst and src in value_dict:
                    args.append(value_dict[src])
                elif src in value_dict or dst in value_dict:
                    args.append((
                        value_dict.get(src, None),
                        value_dict.get(dst, None),
                    ))

            kwargs = {}
            for arg, value_dict in kwargs_dict.items():
                if not arg.endswith("_dict"):
                    raise ValueError(
                        f"Keyword arguments in '{self.__class__.__name__}' "
                        f"need to end with '_dict' (got '{arg}')"
                    )
                clean_arg = arg[:-5]
                if edge_type in value_dict:
                    has_edge_level_arg = True
                    kwargs[clean_arg] = value_dict[edge_type]
                elif src == dst and src in value_dict:
                    kwargs[clean_arg] = value_dict[src]
                elif src in value_dict or dst in value_dict:
                    kwargs[clean_arg] = (
                        value_dict.get(src, None),
                        value_dict.get(dst, None),
                    )

            if not has_edge_level_arg:
                continue

            out = conv(*args, **kwargs)

            if dst not in out_dict:
                out_dict[dst] = [out]
            else:
                out_dict[dst].append(out)

        result: Dict[str, any] = {}
        for key, value in out_dict.items():
            result[key] = group(value, self.aggr)

        return result

